name: Hexlet CI Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '18.x'
#          cache: 'npm'

#      - run npm ci
#      - run npm test

    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: make setup

      - name: run tests
        run: make test

      - name: run linter
        run: make lint

    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: actions/checkout@v4
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
